Repository dwyl/calendar, pull requests merged in 2023-05, with the labels that each got.

#25 [PR] Initial implementation of `calendar`
  .env_example
  .github/workflows/ci.yml
  .github/workflows/deploy.yml
  .gitignore
  BUILDIT.md
  README.md
  assets/js/app.js
  config/config.exs
  config/test.exs
  coveralls.json
  lib/cal/application.ex
  lib/cal/http.ex
  lib/cal/token.ex
  lib/cal_web/components/layouts/app.html.heex
  lib/cal_web/components/layouts/root.html.heex
  lib/cal_web/controllers/google_auth_controller.ex
  lib/cal_web/controllers/page_controller.ex
  lib/cal_web/controllers/page_html/home.html.heex
  lib/cal_web/live/app_live.ex
  lib/cal_web/live/app_live.html.heex
  lib/cal_web/live/app_live_html.ex
  lib/cal_web/router.ex
  mix.exs
  mix.lock
  test/cal_web/controllers/google_auth_controller_test.exs
  test/cal_web/controllers/page_controller_test.exs
  test/cal_web/live/app_live_test.exs
Labels: enhancement, in-review, elixir, documentation, epic

#34 [PR] Fetching token from socket assigns instead of `get_flash`
  BUILDIT.md
  lib/cal_web/live/app_live.ex
Labels: awaiting-review, chore, documentation

#35 PR: Use `gcal` functions + Deploy `gcal.fly.dev` #31
  .gitignore
  Dockerfile
  config/test.exs
  fly.toml
  lib/cal/http.ex
  lib/cal_web/controllers/google_auth_controller.ex
  lib/cal_web/controllers/page_html/home.html.heex
  lib/cal_web/controllers/page_html/privacy.html.heex
  lib/cal_web/live/app_live.ex
  lib/cal_web/live/app_live.html.heex
  lib/cal_web/live/app_live_html.ex
  mix.exs
  mix.lock
  test/cal_web/controllers/page_controller_test.exs
  test/cal_web/live/app_live_test.exs
Labels: enhancement, awaiting-review, elixir, chore

#40 [PR] Remove fix-typos.yml
  .github/workflows/fix-typos.yml
Labels: bug, awaiting-review
